# fly.toml app configuration file generated for kong-dp-default on 2023-05-24T01:34:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kong-dp-default"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  KONG_ADMIN_ERROR_LOG = "/dev/stderr"
  KONG_CLUSTER_MTLS = "pki"
  KONG_DATABASE = "off"
  KONG_DNS_ORDER = "LAST,SRV,A,AAAA,CNAME"
  KONG_KONNECT_MODE = "on"
  KONG_LUA_SSL_TRUSTED_CERTIFICATE = "system"
  KONG_MEM_CACHE_SIZE = "32m"
  KONG_PROXY_ERROR_LOG = "/dev/stderr"
  KONG_ROLE = "data_plane"
  KONG_VITALS = "off"
  KONG_WORKER_PROCESSES = "1"
  KONG_TRUSTED_IPS = "172.16.0.0/16"
  KONG_REAL_IP_HEADER = "fly-client-ip"
  KONG_DEDICATED_CONFIG_PROCESSING = "off"
  KONG_WASM = "on"
  KONG_NGINX_LOCATION_PROXY_SET_HEADER = "Fly-Request-Id ''; proxy_set_header Fly-Region ''; proxy_set_header Fly-Tracestate ''; proxy_set_header Fly-Traceparent ''; proxy_set_header Fly-Forwarded-Ssl ''; proxy_set_header Fly-Forwarded-Proto ''; proxy_set_header Fly-Forwarded-Port ''; proxy_set_header Fly-Client-Ip ''"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6
