# fly.toml file generated for purple-bush-144 on 2021-08-07T16:23:00-07:00

app = "kong-dp-default"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  KONG_ROLE = "data_plane"
  KONG_MEM_CACHE_SIZE = "64m"
  KONG_DATABASE = "off"
  KONG_WORKER_PROCESSES = "1"
  KONG_CLUSTER_MTLS = "pki"
  KONG_PROXY_ERROR_LOG="/dev/stderr"
  KONG_ADMIN_ERROR_LOG="/dev/stderr"
  KONG_LUA_SSL_TRUSTED_CERTIFICATE="system"
  KONG_DNS_ORDER="LAST,SRV,A,AAAA,CNAME"
  KONG_KONNECT_MODE="on"
  KONG_VITALS="off"
#  KONG_PROXY_LISTEN="0.0.0.0:8000 reuseport backlog=16384 http2, 0.0.0.0:8443 http2 ssl reuseport backlog=16384"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"