name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  KONG_CLUSTER_CERT: ${{ secrets.KONG_CLUSTER_CERT }}
  KONG_CLUSTER_CERT_KEY: ${{ secrets.KONG_CLUSTER_CERT_KEY }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl secrets set --detach KONG_CLUSTER_CERT=$KONG_CLUSTER_CERT
        - run: flyctl secrets set --detach KONG_CLUSTER_CERT_KEY=$KONG_CLUSTER_CERT_KEY
        - run: flyctl deploy --remote-only
